/***
-- straight across copy of PM's in Legacy Access DB into CRT 

BEGIN TRANSACTION
SET NOCOUNT ON;

DECLARE @legacyId int, @itemCount int = 10;
DECLARE @legacyName nvarchar(255);

DECLARE pm_cursor CURSOR FOR
	SELECT ID, REPLACE([Full Name], '''', '''''') FROM tblProjectManagers
	WHERE Active = 1 AND 
	ORDER BY [Full Name]

OPEN pm_cursor

WHILE 1 = 1
BEGIN
	FETCH NEXT FROM pm_cursor INTO @legacyId, @legacyName;

	IF @@FETCH_STATUS <> 0
	BEGIN
		BREAK;
	END;

	INSERT INTO CRT_CODE_LOOKUP (CODE_SET, CODE_NAME, CODE_VALUE_TEXT, CODE_VALUE_NUM, DISPLAY_ORDER, CODE_VALUE_FORMAT)
		VALUES ('PROJECT_MANAGER', @legacyName, NULL, NULL, @itemCount, 'STRING');
	
	SET @itemCount = @itemCount + 10;
END;

CLOSE pm_cursor;
DEALLOCATE pm_cursor;

COMMIT
GO

*/

/*** Scripts to retrieve data, inject into appropriate worksheet of excel workbook ./Mapping.xslx

-- retrieve values from Legacy table
SELECT ID, [Full Name] FROM tblProjectManagers
WHERE Active = 1
ORDER BY [Full Name]

--retrieve values from CRT Code Table
SELECT CODE_LOOKUP_ID, CODE_NAME FROM CRT_CODE_LOOKUP
WHERE CODE_SET = 'PROJECT_MANAGER'
AND END_DATE IS NULL
ORDER BY CODE_NAME

***/

BEGIN TRANSACTION

IF OBJECT_ID('dbo.MAP_PROJECT_MANAGER', 'U') IS NOT NULL
	DROP TABLE dbo.MAP_PROJECT_MANAGER;
COMMIT
GO

BEGIN TRANSACTION

CREATE TABLE dbo.MAP_PROJECT_MANAGER
(
	LEGACY_ID numeric(9, 0) NOT NULL,
	CRT_ID numeric(9, 0) NOT NULL
)  ON [PRIMARY]

COMMIT
GO

BEGIN TRANSACTION
SET NOCOUNT ON

INSERT INTO MAP_PROJECT_MANAGER VALUES (279, 923);  --NULL > NULL
INSERT INTO MAP_PROJECT_MANAGER VALUES (353, 924);  --Aaron Barrett > Aaron Barrett
INSERT INTO MAP_PROJECT_MANAGER VALUES (229, 925);  --Abid Sivic > Abid Sivic
INSERT INTO MAP_PROJECT_MANAGER VALUES (443, 926);  --Adam Stubbs > Adam Stubbs
INSERT INTO MAP_PROJECT_MANAGER VALUES (246, 927);  --Adam Veley > Adam Veley
INSERT INTO MAP_PROJECT_MANAGER VALUES (450, 928);  --Adelle Corrado > Adelle Corrado
INSERT INTO MAP_PROJECT_MANAGER VALUES (47, 929);  --Adriana Da Costa > Adriana Da Costa
INSERT INTO MAP_PROJECT_MANAGER VALUES (449, 930);  --Aimee Barre > Aimee Barre
INSERT INTO MAP_PROJECT_MANAGER VALUES (212, 931);  --Al Kennedy > Al Kennedy
INSERT INTO MAP_PROJECT_MANAGER VALUES (74, 932);  --Alan Schmidt > Alan Schmidt
INSERT INTO MAP_PROJECT_MANAGER VALUES (319, 933);  --Alex Crawford > Alex Crawford
INSERT INTO MAP_PROJECT_MANAGER VALUES (290, 934);  --Alex Masun > Alex Masun
INSERT INTO MAP_PROJECT_MANAGER VALUES (406, 935);  --Alex O'Brien > Alex O''Brien
INSERT INTO MAP_PROJECT_MANAGER VALUES (30, 936);  --Alfred Ho > Alfred Ho
INSERT INTO MAP_PROJECT_MANAGER VALUES (305, 937);  --Alicia Kosolofski > Alicia Kosolofski
INSERT INTO MAP_PROJECT_MANAGER VALUES (312, 938);  --Alicia Traas > Alicia Traas
INSERT INTO MAP_PROJECT_MANAGER VALUES (119, 939);  --Allan Galambos > Allan Galambos
INSERT INTO MAP_PROJECT_MANAGER VALUES (314, 940);  --Alley Bates > Alley Bates
INSERT INTO MAP_PROJECT_MANAGER VALUES (333, 941);  --Alysha Piccini > Alysha Piccini
INSERT INTO MAP_PROJECT_MANAGER VALUES (59, 942);  --Alyssa Morice > Alyssa Morice
INSERT INTO MAP_PROJECT_MANAGER VALUES (322, 943);  --Alyssa Schultz > Alyssa Schultz
INSERT INTO MAP_PROJECT_MANAGER VALUES (339, 944);  --Amandeep Dhaliwal > Amandeep Dhaliwal
INSERT INTO MAP_PROJECT_MANAGER VALUES (163, 945);  --Ameilia Adams > Ameilia Adams
INSERT INTO MAP_PROJECT_MANAGER VALUES (8, 946);  --Amy Tsang > Amy Tsang
INSERT INTO MAP_PROJECT_MANAGER VALUES (9, 947);  --Andrew Hind > Andrew Hind
INSERT INTO MAP_PROJECT_MANAGER VALUES (323, 948);  --Andrew Swift > Andrew Swift
INSERT INTO MAP_PROJECT_MANAGER VALUES (341, 949);  --Andrew Swift > Andrew Swift
INSERT INTO MAP_PROJECT_MANAGER VALUES (158, 950);  --Angie Allwood > Angie Allwood
INSERT INTO MAP_PROJECT_MANAGER VALUES (282, 951);  --Anna Kosmala > Anna Kosmala
INSERT INTO MAP_PROJECT_MANAGER VALUES (433, 952);  --Anton Stefanac > Anton Stefanac
INSERT INTO MAP_PROJECT_MANAGER VALUES (286, 953);  --Arkesteyn Mikayla > Arkesteyn Mikayla
INSERT INTO MAP_PROJECT_MANAGER VALUES (86, 954);  --Art McLean > Art McLean
INSERT INTO MAP_PROJECT_MANAGER VALUES (424, 955);  --Ashley Cousens > Ashley Cousens
INSERT INTO MAP_PROJECT_MANAGER VALUES (244, 956);  --Ashok Bhatti > Ashok Bhatti
INSERT INTO MAP_PROJECT_MANAGER VALUES (377, 957);  --August Sheldon > August Sheldon
INSERT INTO MAP_PROJECT_MANAGER VALUES (127, 958);  --Bart Chenuz > Bart Chenuz
INSERT INTO MAP_PROJECT_MANAGER VALUES (326, 959);  --Beau Annunziello > Beau Annunziello
INSERT INTO MAP_PROJECT_MANAGER VALUES (97, 960);  --Beau Sutherland > Beau Sutherland
INSERT INTO MAP_PROJECT_MANAGER VALUES (421, 961);  --Ben Reinbolt > Ben Reinbolt
INSERT INTO MAP_PROJECT_MANAGER VALUES (393, 962);  --Ben Reinbolt > Ben Reinbolt
INSERT INTO MAP_PROJECT_MANAGER VALUES (254, 963);  --Ben Tanasichuk > Ben Tanasichuk
INSERT INTO MAP_PROJECT_MANAGER VALUES (128, 964);  --Bill Becker > Bill Becker
INSERT INTO MAP_PROJECT_MANAGER VALUES (16, 965);  --Bill Crichton > Bill Crichton
INSERT INTO MAP_PROJECT_MANAGER VALUES (122, 966);  --Bill Glen > Bill Glen
INSERT INTO MAP_PROJECT_MANAGER VALUES (196, 967);  --Bill Leitch > Bill Leitch
INSERT INTO MAP_PROJECT_MANAGER VALUES (54, 968);  --Bill Rose > Bill Rose
INSERT INTO MAP_PROJECT_MANAGER VALUES (38, 969);  --Bob Alexandruk > Bob Alexandruk
INSERT INTO MAP_PROJECT_MANAGER VALUES (336, 970);  --Bonnie Meints > Bonnie Meints
INSERT INTO MAP_PROJECT_MANAGER VALUES (329, 971);  --Brad Beaupre > Brad Beaupre
INSERT INTO MAP_PROJECT_MANAGER VALUES (143, 972);  --Brad Boyden > Brad Boyden
INSERT INTO MAP_PROJECT_MANAGER VALUES (15, 973);  --Brad Bushill > Brad Bushill
INSERT INTO MAP_PROJECT_MANAGER VALUES (217, 974);  --Brad Hogg > Brad Hogg
INSERT INTO MAP_PROJECT_MANAGER VALUES (70, 975);  --Brad Moores > Brad Moores
INSERT INTO MAP_PROJECT_MANAGER VALUES (311, 976);  --Brad Panton > Brad Panton
INSERT INTO MAP_PROJECT_MANAGER VALUES (397, 977);  --Brandon Klingbell > Brandon Klingbell
INSERT INTO MAP_PROJECT_MANAGER VALUES (40, 978);  --Brent Cameron > Brent Cameron
INSERT INTO MAP_PROJECT_MANAGER VALUES (367, 979);  --Brent Case > Brent Case
INSERT INTO MAP_PROJECT_MANAGER VALUES (67, 980);  --Brent Davies > Brent Davies
INSERT INTO MAP_PROJECT_MANAGER VALUES (198, 981);  --Brent McDonald > Brent McDonald
INSERT INTO MAP_PROJECT_MANAGER VALUES (202, 982);  --Brent Persello > Brent Persello
INSERT INTO MAP_PROJECT_MANAGER VALUES (368, 983);  --Brian Lomas > Brian Lomas
INSERT INTO MAP_PROJECT_MANAGER VALUES (55, 984);  --Brian Taylor > Brian Taylor
INSERT INTO MAP_PROJECT_MANAGER VALUES (34, 985);  --Brigid Canil > Brigid Canil
INSERT INTO MAP_PROJECT_MANAGER VALUES (273, 986);  --Brooke Casby > Brooke Casby
INSERT INTO MAP_PROJECT_MANAGER VALUES (48, 987);  --Brooke Clasby > Brooke Clasby
INSERT INTO MAP_PROJECT_MANAGER VALUES (99, 988);  --Bryan Crosby > Bryan Crosby
INSERT INTO MAP_PROJECT_MANAGER VALUES (366, 989);  --Cailey Brown > Cailey Brown
INSERT INTO MAP_PROJECT_MANAGER VALUES (227, 990);  --Caitlin Dobson > Caitlin Dobson
INSERT INTO MAP_PROJECT_MANAGER VALUES (83, 991);  --Carolyn Turcotte > Carolyn Turcotte
INSERT INTO MAP_PROJECT_MANAGER VALUES (62, 992);  --Catherine Bartlett > Catherine Bartlett
INSERT INTO MAP_PROJECT_MANAGER VALUES (384, 993);  --Catherine Bartlett > Catherine Bartlett
INSERT INTO MAP_PROJECT_MANAGER VALUES (78, 994);  --Cecil Bianco > Cecil Bianco
INSERT INTO MAP_PROJECT_MANAGER VALUES (18, 995);  --Cedric Evangelista > Cedric Evangelista
INSERT INTO MAP_PROJECT_MANAGER VALUES (12, 996);  --Cedrick Evangelista > Cedrick Evangelista
INSERT INTO MAP_PROJECT_MANAGER VALUES (185, 997);  --Chad Marsh > Chad Marsh
INSERT INTO MAP_PROJECT_MANAGER VALUES (14, 998);  --Chad Siemens > Chad Siemens
INSERT INTO MAP_PROJECT_MANAGER VALUES (176, 999);  --Chris Gordon  > Chris Gordon 
INSERT INTO MAP_PROJECT_MANAGER VALUES (80, 1000);  --Chris Keir > Chris Keir
INSERT INTO MAP_PROJECT_MANAGER VALUES (243, 1001);  --Chris Lee > Chris Lee
INSERT INTO MAP_PROJECT_MANAGER VALUES (404, 1002);  --Christine Ingham > Christine Ingham
INSERT INTO MAP_PROJECT_MANAGER VALUES (77, 1003);  --Clayton Tomas > Clayton Tomas
INSERT INTO MAP_PROJECT_MANAGER VALUES (278, 1004);  --Clint Monson  > Clint Monson 
INSERT INTO MAP_PROJECT_MANAGER VALUES (180, 1005);  --Clint Monson > Clint Monson
INSERT INTO MAP_PROJECT_MANAGER VALUES (213, 1006);  --Colin Midgley > Colin Midgley
INSERT INTO MAP_PROJECT_MANAGER VALUES (76, 1007);  --Colleen Davis > Colleen Davis
INSERT INTO MAP_PROJECT_MANAGER VALUES (390, 1008);  --Corey Peterson > Corey Peterson
INSERT INTO MAP_PROJECT_MANAGER VALUES (239, 1009);  --Corinna Ellerman > Corinna Ellerman
INSERT INTO MAP_PROJECT_MANAGER VALUES (318, 1010);  --Cory Schmidt > Cory Schmidt
INSERT INTO MAP_PROJECT_MANAGER VALUES (401, 1011);  --Courtenay Nicol > Courtenay Nicol
INSERT INTO MAP_PROJECT_MANAGER VALUES (301, 1012);  --Curtis Saunders > Curtis Saunders
INSERT INTO MAP_PROJECT_MANAGER VALUES (169, 1013);  --Dan Baker > Dan Baker
INSERT INTO MAP_PROJECT_MANAGER VALUES (417, 1014);  --Dan Brooks > Dan Brooks
INSERT INTO MAP_PROJECT_MANAGER VALUES (147, 1015);  --Dan Olson > Dan Olson
INSERT INTO MAP_PROJECT_MANAGER VALUES (32, 1016);  --Dana Aljanaby  > Dana Aljanaby 
INSERT INTO MAP_PROJECT_MANAGER VALUES (370, 1017);  --Daniel Belisle > Daniel Belisle
INSERT INTO MAP_PROJECT_MANAGER VALUES (369, 1018);  --Daniel Cossette > Daniel Cossette
INSERT INTO MAP_PROJECT_MANAGER VALUES (429, 1019);  --Daniel Johnson > Daniel Johnson
INSERT INTO MAP_PROJECT_MANAGER VALUES (316, 1020);  --Danielle Dessureault > Danielle Dessureault
INSERT INTO MAP_PROJECT_MANAGER VALUES (388, 1021);  --Danielle French > Danielle French
INSERT INTO MAP_PROJECT_MANAGER VALUES (351, 1022);  --Danny Arndt > Danny Arndt
INSERT INTO MAP_PROJECT_MANAGER VALUES (44, 1023);  --Danny Morris > Danny Morris
INSERT INTO MAP_PROJECT_MANAGER VALUES (193, 1024);  --Darcy Grykuliak > Darcy Grykuliak
INSERT INTO MAP_PROJECT_MANAGER VALUES (136, 1025);  --Darcy Penner > Darcy Penner
INSERT INTO MAP_PROJECT_MANAGER VALUES (211, 1026);  --Darin Welch > Darin Welch
INSERT INTO MAP_PROJECT_MANAGER VALUES (150, 1027);  --Darrell Gunn > Darrell Gunn
INSERT INTO MAP_PROJECT_MANAGER VALUES (134, 1028);  --Darren Englund > Darren Englund
INSERT INTO MAP_PROJECT_MANAGER VALUES (249, 1029);  --Daryl Nolan > Daryl Nolan
INSERT INTO MAP_PROJECT_MANAGER VALUES (164, 1030);  --Dave Edgar > Dave Edgar
INSERT INTO MAP_PROJECT_MANAGER VALUES (200, 1031);  --Dave Prehara > Dave Prehara
INSERT INTO MAP_PROJECT_MANAGER VALUES (257, 1032);  --Dave Sarsiat > Dave Sarsiat
INSERT INTO MAP_PROJECT_MANAGER VALUES (49, 1033);  --Dave Shibata > Dave Shibata
INSERT INTO MAP_PROJECT_MANAGER VALUES (220, 1034);  --Dave Swales > Dave Swales
INSERT INTO MAP_PROJECT_MANAGER VALUES (338, 1035);  --Daveena Thomas > Daveena Thomas
INSERT INTO MAP_PROJECT_MANAGER VALUES (340, 1036);  --David Chang > David Chang
INSERT INTO MAP_PROJECT_MANAGER VALUES (378, 1037);  --David Gerein > David Gerein
INSERT INTO MAP_PROJECT_MANAGER VALUES (23, 1038);  --David Holloway > David Holloway
INSERT INTO MAP_PROJECT_MANAGER VALUES (117, 1039);  --David Keely > David Keely
INSERT INTO MAP_PROJECT_MANAGER VALUES (179, 1040);  --David Mintak > David Mintak
INSERT INTO MAP_PROJECT_MANAGER VALUES (320, 1041);  --David Retzer > David Retzer
INSERT INTO MAP_PROJECT_MANAGER VALUES (240, 1042);  --Dean Daniel > Dean Daniel
INSERT INTO MAP_PROJECT_MANAGER VALUES (27, 1043);  --Deborah Newby > Deborah Newby
INSERT INTO MAP_PROJECT_MANAGER VALUES (17, 1044);  --Deborah Tan > Deborah Tan
INSERT INTO MAP_PROJECT_MANAGER VALUES (349, 1045);  --Dejan Pesic > Dejan Pesic
INSERT INTO MAP_PROJECT_MANAGER VALUES (112, 1046);  --Dennis Kurylowich > Dennis Kurylowich
INSERT INTO MAP_PROJECT_MANAGER VALUES (5, 1047);  --Derek Drummond > Derek Drummond
INSERT INTO MAP_PROJECT_MANAGER VALUES (317, 1048);  --Derek Kitamura > Derek Kitamura
INSERT INTO MAP_PROJECT_MANAGER VALUES (22, 1049);  --Dickson Chung > Dickson Chung
INSERT INTO MAP_PROJECT_MANAGER VALUES (237, 1050);  --District Staff > District Staff
INSERT INTO MAP_PROJECT_MANAGER VALUES (182, 1051);  --DJ Bella > DJ Bella
INSERT INTO MAP_PROJECT_MANAGER VALUES (258, 1052);  --Dominko Komnenovic > Dominko Komnenovic
INSERT INTO MAP_PROJECT_MANAGER VALUES (413, 1053);  --Don Hounsell > Don Hounsell
INSERT INTO MAP_PROJECT_MANAGER VALUES (20, 1054);  --Don Legault > Don Legault
INSERT INTO MAP_PROJECT_MANAGER VALUES (204, 1055);  --Don Shaw > Don Shaw
INSERT INTO MAP_PROJECT_MANAGER VALUES (126, 1056);  --Donalda Ritchie > Donalda Ritchie
INSERT INTO MAP_PROJECT_MANAGER VALUES (168, 1057);  --Donovan Gee > Donovan Gee
INSERT INTO MAP_PROJECT_MANAGER VALUES (26, 1058);  --Doug Hyde > Doug Hyde
INSERT INTO MAP_PROJECT_MANAGER VALUES (350, 1059);  --Doug Wilson > Doug Wilson
INSERT INTO MAP_PROJECT_MANAGER VALUES (428, 1060);  --Duane Wells > Duane Wells
INSERT INTO MAP_PROJECT_MANAGER VALUES (391, 1061);  --Dylan Bennett > Dylan Bennett
INSERT INTO MAP_PROJECT_MANAGER VALUES (304, 1062);  --Emily Fukumoto > Emily Fukumoto
INSERT INTO MAP_PROJECT_MANAGER VALUES (346, 1063);  --Emma MacTavish > Emma MacTavish
INSERT INTO MAP_PROJECT_MANAGER VALUES (357, 1064);  --Eric Julien > Eric Julien
INSERT INTO MAP_PROJECT_MANAGER VALUES (347, 1065);  --Eric Kronlacher > Eric Kronlacher
INSERT INTO MAP_PROJECT_MANAGER VALUES (64, 1066);  --Eric Lachmuth > Eric Lachmuth
INSERT INTO MAP_PROJECT_MANAGER VALUES (422, 1067);  --Erik Jamik > Erik Jamik
INSERT INTO MAP_PROJECT_MANAGER VALUES (46, 1068);  --Erik Lachmuth > Erik Lachmuth
INSERT INTO MAP_PROJECT_MANAGER VALUES (29, 1069);  --Erin Moxon > Erin Moxon
INSERT INTO MAP_PROJECT_MANAGER VALUES (79, 1070);  --Faisal Siddiqui > Faisal Siddiqui
INSERT INTO MAP_PROJECT_MANAGER VALUES (233, 1071);  --Felix Latour - 37288, Florian Kund - 37291 > Felix Latour - 37288, Florian Kund - 37291
INSERT INTO MAP_PROJECT_MANAGER VALUES (234, 1072);  --Florian Kund > Florian Kund
INSERT INTO MAP_PROJECT_MANAGER VALUES (436, 1073);  --Francois Laurent > Francois Laurent
INSERT INTO MAP_PROJECT_MANAGER VALUES (171, 1074);  --Fred Seychuk > Fred Seychuk
INSERT INTO MAP_PROJECT_MANAGER VALUES (21, 1075);  --Gateway  > Gateway 
INSERT INTO MAP_PROJECT_MANAGER VALUES (43, 1076);  --Gayle Keefe > Gayle Keefe
INSERT INTO MAP_PROJECT_MANAGER VALUES (75, 1077);  --George Lomas > George Lomas
INSERT INTO MAP_PROJECT_MANAGER VALUES (221, 1078);  --George Warnock > George Warnock
INSERT INTO MAP_PROJECT_MANAGER VALUES (380, 1079);  --Gerri Goulet > Gerri Goulet
INSERT INTO MAP_PROJECT_MANAGER VALUES (89, 1080);  --Gerry Fleming > Gerry Fleming
INSERT INTO MAP_PROJECT_MANAGER VALUES (173, 1081);  --Giesila Decker  > Giesila Decker 
INSERT INTO MAP_PROJECT_MANAGER VALUES (152, 1082);  --Gord Bonwick > Gord Bonwick
INSERT INTO MAP_PROJECT_MANAGER VALUES (88, 1083);  --Gord Chudleigh > Gord Chudleigh
INSERT INTO MAP_PROJECT_MANAGER VALUES (376, 1084);  --Gordon H Wagner > Gordon H Wagner
INSERT INTO MAP_PROJECT_MANAGER VALUES (10, 1085);  --Graeme Schimpf > Graeme Schimpf
INSERT INTO MAP_PROJECT_MANAGER VALUES (415, 1086);  --Grant Erickson > Grant Erickson
INSERT INTO MAP_PROJECT_MANAGER VALUES (381, 1087);  --Grant Herman > Grant Herman
INSERT INTO MAP_PROJECT_MANAGER VALUES (104, 1088);  --Grant Smith > Grant Smith
INSERT INTO MAP_PROJECT_MANAGER VALUES (146, 1089);  --Grant Watson > Grant Watson
INSERT INTO MAP_PROJECT_MANAGER VALUES (115, 1090);  --Greg Bruce > Greg Bruce
INSERT INTO MAP_PROJECT_MANAGER VALUES (139, 1091);  --Greg Kinnear > Greg Kinnear
INSERT INTO MAP_PROJECT_MANAGER VALUES (141, 1092);  --Greg Ross > Greg Ross
INSERT INTO MAP_PROJECT_MANAGER VALUES (58, 1093);  --Hali Davenport > Hali Davenport
INSERT INTO MAP_PROJECT_MANAGER VALUES (24, 1094);  --Helen Evans > Helen Evans
INSERT INTO MAP_PROJECT_MANAGER VALUES (124, 1095);  --Hilary Barnett > Hilary Barnett
INSERT INTO MAP_PROJECT_MANAGER VALUES (423, 1096);  --Holden Spencer > Holden Spencer
INSERT INTO MAP_PROJECT_MANAGER VALUES (342, 1097);  --Ian Grant > Ian Grant
INSERT INTO MAP_PROJECT_MANAGER VALUES (328, 1098);  --Ian Mandrusiak > Ian Mandrusiak
INSERT INTO MAP_PROJECT_MANAGER VALUES (382, 1099);  --Irene Pearce > Irene Pearce
INSERT INTO MAP_PROJECT_MANAGER VALUES (395, 1100);  --James Dash > James Dash
INSERT INTO MAP_PROJECT_MANAGER VALUES (262, 1101);  --James Hewitt > James Hewitt
INSERT INTO MAP_PROJECT_MANAGER VALUES (386, 1102);  --James Luo > James Luo
INSERT INTO MAP_PROJECT_MANAGER VALUES (451, 1103);  --Jamie Goodridge > Jamie Goodridge
INSERT INTO MAP_PROJECT_MANAGER VALUES (129, 1104);  --Janelle Erwin > Janelle Erwin
INSERT INTO MAP_PROJECT_MANAGER VALUES (372, 1105);  --Janet Colussi > Janet Colussi
INSERT INTO MAP_PROJECT_MANAGER VALUES (298, 1106);  --Jarret Wedel > Jarret Wedel
INSERT INTO MAP_PROJECT_MANAGER VALUES (148, 1107);  --Jason Templeton > Jason Templeton
INSERT INTO MAP_PROJECT_MANAGER VALUES (135, 1108);  --Jay Dunbar > Jay Dunbar
INSERT INTO MAP_PROJECT_MANAGER VALUES (1, 1109);  --Jay Porter > Jay Porter
INSERT INTO MAP_PROJECT_MANAGER VALUES (383, 1110);  --Jayson Chaplin > Jayson Chaplin
INSERT INTO MAP_PROJECT_MANAGER VALUES (418, 1111);  --Jeanette Grant > Jeanette Grant
INSERT INTO MAP_PROJECT_MANAGER VALUES (68, 1112);  --Jed Zimmerman > Jed Zimmerman
INSERT INTO MAP_PROJECT_MANAGER VALUES (189, 1113);  --Jeff Ferguson > Jeff Ferguson
INSERT INTO MAP_PROJECT_MANAGER VALUES (203, 1114);  --Jeff Saby > Jeff Saby
INSERT INTO MAP_PROJECT_MANAGER VALUES (25, 1115);  --Jennifer Locke > Jennifer Locke
INSERT INTO MAP_PROJECT_MANAGER VALUES (306, 1116);  --Jennifer Stites > Jennifer Stites
INSERT INTO MAP_PROJECT_MANAGER VALUES (28, 1117);  --Jesse Morwood  > Jesse Morwood 
INSERT INTO MAP_PROJECT_MANAGER VALUES (402, 1118);  --Jessica Learn > Jessica Learn
INSERT INTO MAP_PROJECT_MANAGER VALUES (426, 1119);  --Jessica Zylicz > Jessica Zylicz
INSERT INTO MAP_PROJECT_MANAGER VALUES (420, 1120);  --Jessie Horton > Jessie Horton
INSERT INTO MAP_PROJECT_MANAGER VALUES (251, 1121);  --Jim White > Jim White
INSERT INTO MAP_PROJECT_MANAGER VALUES (444, 1122);  --Jo Cowper > Jo Cowper
INSERT INTO MAP_PROJECT_MANAGER VALUES (431, 1123);  --Jody Deane > Jody Deane
INSERT INTO MAP_PROJECT_MANAGER VALUES (399, 1124);  --Joey Tasker > Joey Tasker
INSERT INTO MAP_PROJECT_MANAGER VALUES (210, 1125);  --John Babineau > John Babineau
INSERT INTO MAP_PROJECT_MANAGER VALUES (294, 1126);  --John Marchesan > John Marchesan
INSERT INTO MAP_PROJECT_MANAGER VALUES (92, 1127);  --John Schnablegger > John Schnablegger
INSERT INTO MAP_PROJECT_MANAGER VALUES (264, 1128);  --John Snyder > John Snyder
INSERT INTO MAP_PROJECT_MANAGER VALUES (172, 1129);  --John Van Geloven > John Van Geloven
INSERT INTO MAP_PROJECT_MANAGER VALUES (192, 1130);  --Jon Jensen > Jon Jensen
INSERT INTO MAP_PROJECT_MANAGER VALUES (133, 1131);  --Jonathan Tillie > Jonathan Tillie
INSERT INTO MAP_PROJECT_MANAGER VALUES (256, 1132);  --Jonathan Tillies > Jonathan Tillies
INSERT INTO MAP_PROJECT_MANAGER VALUES (114, 1133);  --Joseph Adom > Joseph Adom
INSERT INTO MAP_PROJECT_MANAGER VALUES (197, 1134);  --Joyce Chang > Joyce Chang
INSERT INTO MAP_PROJECT_MANAGER VALUES (222, 1135);  --JP Fournier > JP Fournier
INSERT INTO MAP_PROJECT_MANAGER VALUES (111, 1136);  --Jurgen Lutter > Jurgen Lutter
INSERT INTO MAP_PROJECT_MANAGER VALUES (270, 1137);  --Karamjeet Degan > Karamjeet Degan
INSERT INTO MAP_PROJECT_MANAGER VALUES (151, 1138);  --Kareen Peters > Kareen Peters
INSERT INTO MAP_PROJECT_MANAGER VALUES (56, 1139);  --Karen Andrews > Karen Andrews
INSERT INTO MAP_PROJECT_MANAGER VALUES (300, 1140);  --Kasey Foyston > Kasey Foyston
INSERT INTO MAP_PROJECT_MANAGER VALUES (63, 1141);  --Kassidi Jones > Kassidi Jones
INSERT INTO MAP_PROJECT_MANAGER VALUES (440, 1142);  --Kathy Crawford > Kathy Crawford
INSERT INTO MAP_PROJECT_MANAGER VALUES (11, 1143);  --Kathy Strobbe > Kathy Strobbe
INSERT INTO MAP_PROJECT_MANAGER VALUES (138, 1144);  --Katie Ward > Katie Ward
INSERT INTO MAP_PROJECT_MANAGER VALUES (19, 1145);  --Keith Lastoria  > Keith Lastoria 
INSERT INTO MAP_PROJECT_MANAGER VALUES (331, 1146);  --Keith Lastoria > Keith Lastoria
INSERT INTO MAP_PROJECT_MANAGER VALUES (101, 1147);  --Kellen Truant > Kellen Truant
INSERT INTO MAP_PROJECT_MANAGER VALUES (61, 1148);  --Ken Aura > Ken Aura
INSERT INTO MAP_PROJECT_MANAGER VALUES (285, 1149);  --Ken Namislo > Ken Namislo
INSERT INTO MAP_PROJECT_MANAGER VALUES (93, 1150);  --Kenedee Ludwar > Kenedee Ludwar
INSERT INTO MAP_PROJECT_MANAGER VALUES (165, 1151);  --Kent Hodgson > Kent Hodgson
INSERT INTO MAP_PROJECT_MANAGER VALUES (283, 1152);  --Kevin Carter > Kevin Carter
INSERT INTO MAP_PROJECT_MANAGER VALUES (414, 1153);  --Kevin Lutz > Kevin Lutz
INSERT INTO MAP_PROJECT_MANAGER VALUES (295, 1154);  --Kevyn Hryhirchuk > Kevyn Hryhirchuk
INSERT INTO MAP_PROJECT_MANAGER VALUES (408, 1155);  --Khalid Khan > Khalid Khan
INSERT INTO MAP_PROJECT_MANAGER VALUES (425, 1156);  --Kirk Normand > Kirk Normand
INSERT INTO MAP_PROJECT_MANAGER VALUES (364, 1157);  --Kirsten Konge > Kirsten Konge
INSERT INTO MAP_PROJECT_MANAGER VALUES (412, 1158);  --Korry Bonhomme > Korry Bonhomme
INSERT INTO MAP_PROJECT_MANAGER VALUES (432, 1159);  --Kristen Johnson > Kristen Johnson
INSERT INTO MAP_PROJECT_MANAGER VALUES (107, 1160);  --Kristen Spearman  > Kristen Spearman 
INSERT INTO MAP_PROJECT_MANAGER VALUES (6, 1161);  --Kyle Drummond > Kyle Drummond
INSERT INTO MAP_PROJECT_MANAGER VALUES (409, 1162);  --Kyle Drummond > Kyle Drummond
INSERT INTO MAP_PROJECT_MANAGER VALUES (419, 1163);  --Kyle Halvorson > Kyle Halvorson
INSERT INTO MAP_PROJECT_MANAGER VALUES (94, 1164);  --Kylee O’Dell  > Kylee O’Dell 
INSERT INTO MAP_PROJECT_MANAGER VALUES (157, 1165);  --Larry Park > Larry Park
INSERT INTO MAP_PROJECT_MANAGER VALUES (379, 1166);  --Laura Herrera > Laura Herrera
INSERT INTO MAP_PROJECT_MANAGER VALUES (400, 1167);  --Lauren Bell > Lauren Bell
INSERT INTO MAP_PROJECT_MANAGER VALUES (430, 1168);  --Lauren Scott > Lauren Scott
INSERT INTO MAP_PROJECT_MANAGER VALUES (263, 1169);  --Laurie Christiansen > Laurie Christiansen
INSERT INTO MAP_PROJECT_MANAGER VALUES (161, 1170);  --Leanne Ilnicki > Leanne Ilnicki
INSERT INTO MAP_PROJECT_MANAGER VALUES (160, 1171);  --Leeah Reese > Leeah Reese
INSERT INTO MAP_PROJECT_MANAGER VALUES (205, 1172);  --Leeah Tappert > Leeah Tappert
INSERT INTO MAP_PROJECT_MANAGER VALUES (51, 1173);  --Len Sauchuk > Len Sauchuk
INSERT INTO MAP_PROJECT_MANAGER VALUES (187, 1174);  --Les Gilburg > Les Gilburg
INSERT INTO MAP_PROJECT_MANAGER VALUES (90, 1175);  --Lina Halwani > Lina Halwani
INSERT INTO MAP_PROJECT_MANAGER VALUES (389, 1176);  --Lindsay McKinnon > Lindsay McKinnon
INSERT INTO MAP_PROJECT_MANAGER VALUES (52, 1177);  --Lindsay Parker > Lindsay Parker
INSERT INTO MAP_PROJECT_MANAGER VALUES (118, 1178);  --Lisa Amminson > Lisa Amminson
INSERT INTO MAP_PROJECT_MANAGER VALUES (31, 1179);  --Lisa Miller > Lisa Miller
INSERT INTO MAP_PROJECT_MANAGER VALUES (206, 1180);  --Loreen Russel > Loreen Russel
INSERT INTO MAP_PROJECT_MANAGER VALUES (13, 1181);  --Loris Tommasel > Loris Tommasel
INSERT INTO MAP_PROJECT_MANAGER VALUES (154, 1182);  --Louis Sun > Louis Sun
INSERT INTO MAP_PROJECT_MANAGER VALUES (153, 1183);  --Louise Sun > Louise Sun
INSERT INTO MAP_PROJECT_MANAGER VALUES (445, 1184);  --Lucill Green > Lucill Green
INSERT INTO MAP_PROJECT_MANAGER VALUES (159, 1185);  --Lynn Ann Cheverie > Lynn Ann Cheverie
INSERT INTO MAP_PROJECT_MANAGER VALUES (296, 1186);  --Lynn Ann Cheverie > Lynn Ann Cheverie
INSERT INTO MAP_PROJECT_MANAGER VALUES (437, 1187);  --Mackenzie Berry > Mackenzie Berry
INSERT INTO MAP_PROJECT_MANAGER VALUES (53, 1188);  --Maike Schimpf > Maike Schimpf
INSERT INTO MAP_PROJECT_MANAGER VALUES (232, 1189);  --Marcus Barber > Marcus Barber
INSERT INTO MAP_PROJECT_MANAGER VALUES (69, 1190);  --Margie Henley > Margie Henley
INSERT INTO MAP_PROJECT_MANAGER VALUES (411, 1191);  --Marie Wood > Marie Wood
INSERT INTO MAP_PROJECT_MANAGER VALUES (177, 1192);  --Mark Louttit > Mark Louttit
INSERT INTO MAP_PROJECT_MANAGER VALUES (260, 1193);  --Mark Savage > Mark Savage
INSERT INTO MAP_PROJECT_MANAGER VALUES (310, 1194);  --Marleen Keehn > Marleen Keehn
INSERT INTO MAP_PROJECT_MANAGER VALUES (137, 1195);  --Marvin Jones > Marvin Jones
INSERT INTO MAP_PROJECT_MANAGER VALUES (373, 1196);  --Matt Foley > Matt Foley
INSERT INTO MAP_PROJECT_MANAGER VALUES (175, 1197);  --Matthew Bond > Matthew Bond
INSERT INTO MAP_PROJECT_MANAGER VALUES (435, 1198);  --Matthew Butterfield > Matthew Butterfield
INSERT INTO MAP_PROJECT_MANAGER VALUES (335, 1199);  --Maurice LaFrancois > Maurice LaFrancois
INSERT INTO MAP_PROJECT_MANAGER VALUES (195, 1200);  --Maurice LeFrancois > Maurice LeFrancois
INSERT INTO MAP_PROJECT_MANAGER VALUES (325, 1201);  --Max Birkner > Max Birkner
INSERT INTO MAP_PROJECT_MANAGER VALUES (268, 1202);  --Maziar Kazemi  > Maziar Kazemi 
INSERT INTO MAP_PROJECT_MANAGER VALUES (324, 1203);  --Michael Blancher > Michael Blancher
INSERT INTO MAP_PROJECT_MANAGER VALUES (354, 1204);  --Michael Braun > Michael Braun
INSERT INTO MAP_PROJECT_MANAGER VALUES (4, 1205);  --Michael Dinney > Michael Dinney
INSERT INTO MAP_PROJECT_MANAGER VALUES (442, 1206);  --Michelle Bell > Michelle Bell
INSERT INTO MAP_PROJECT_MANAGER VALUES (407, 1207);  --Michelle Boudreau > Michelle Boudreau
INSERT INTO MAP_PROJECT_MANAGER VALUES (194, 1208);  --Michelle Evans > Michelle Evans
INSERT INTO MAP_PROJECT_MANAGER VALUES (57, 1209);  --Michelle Schilling > Michelle Schilling
INSERT INTO MAP_PROJECT_MANAGER VALUES (293, 1210);  --Mikayla Arkesteyn > Mikayla Arkesteyn
INSERT INTO MAP_PROJECT_MANAGER VALUES (41, 1211);  --Mike Aldred > Mike Aldred
INSERT INTO MAP_PROJECT_MANAGER VALUES (130, 1212);  --Mike Boissoneault > Mike Boissoneault
INSERT INTO MAP_PROJECT_MANAGER VALUES (149, 1213);  --Mike Dinney > Mike Dinney
INSERT INTO MAP_PROJECT_MANAGER VALUES (170, 1214);  --Mike Dolman > Mike Dolman
INSERT INTO MAP_PROJECT_MANAGER VALUES (447, 1215);  --Mike Frazier > Mike Frazier
INSERT INTO MAP_PROJECT_MANAGER VALUES (96, 1216);  --Mike Kelly > Mike Kelly
INSERT INTO MAP_PROJECT_MANAGER VALUES (207, 1217);  --Mike Lorimer > Mike Lorimer
INSERT INTO MAP_PROJECT_MANAGER VALUES (85, 1218);  --Mike Matejka > Mike Matejka
INSERT INTO MAP_PROJECT_MANAGER VALUES (267, 1219);  --Mike Odowichuk > Mike Odowichuk
INSERT INTO MAP_PROJECT_MANAGER VALUES (132, 1220);  --Mike Pearson > Mike Pearson
INSERT INTO MAP_PROJECT_MANAGER VALUES (446, 1221);  --Millie Furlong > Millie Furlong
INSERT INTO MAP_PROJECT_MANAGER VALUES (365, 1222);  --Mohsin Gohir > Mohsin Gohir
INSERT INTO MAP_PROJECT_MANAGER VALUES (361, 1223);  --Monique Gairns > Monique Gairns
INSERT INTO MAP_PROJECT_MANAGER VALUES (253, 1224);  --Nadia Lebel > Nadia Lebel
INSERT INTO MAP_PROJECT_MANAGER VALUES (259, 1225);  --Nash Jamal > Nash Jamal
INSERT INTO MAP_PROJECT_MANAGER VALUES (174, 1226);  --Nassir Malik > Nassir Malik
INSERT INTO MAP_PROJECT_MANAGER VALUES (410, 1227);  --Nathan Lepoudre > Nathan Lepoudre
INSERT INTO MAP_PROJECT_MANAGER VALUES (7, 1228);  --Nathan Voogd > Nathan Voogd
INSERT INTO MAP_PROJECT_MANAGER VALUES (358, 1229);  --Neal Moulton > Neal Moulton
INSERT INTO MAP_PROJECT_MANAGER VALUES (356, 1230);  --Neal Moulton > Neal Moulton
INSERT INTO MAP_PROJECT_MANAGER VALUES (188, 1231);  --Neetu Bhatti > Neetu Bhatti
INSERT INTO MAP_PROJECT_MANAGER VALUES (345, 1232);  --Nicola Hogg > Nicola Hogg
INSERT INTO MAP_PROJECT_MANAGER VALUES (405, 1233);  --Nicole Folk > Nicole Folk
INSERT INTO MAP_PROJECT_MANAGER VALUES (247, 1234);  --Nini Long > Nini Long
INSERT INTO MAP_PROJECT_MANAGER VALUES (100, 1235);  --Oliver Schwuchow > Oliver Schwuchow
INSERT INTO MAP_PROJECT_MANAGER VALUES (281, 1236);  --Pat Devereaux > Pat Devereaux
INSERT INTO MAP_PROJECT_MANAGER VALUES (261, 1237);  --Pat Egan > Pat Egan
INSERT INTO MAP_PROJECT_MANAGER VALUES (265, 1238);  --Patrica Mazuck > Patrica Mazuck
INSERT INTO MAP_PROJECT_MANAGER VALUES (33, 1239);  --Patrick Coates > Patrick Coates
INSERT INTO MAP_PROJECT_MANAGER VALUES (348, 1240);  --Paul Rae > Paul Rae
INSERT INTO MAP_PROJECT_MANAGER VALUES (125, 1241);  --Paul Riegert > Paul Riegert
INSERT INTO MAP_PROJECT_MANAGER VALUES (332, 1242);  --Paul Savinkoff > Paul Savinkoff
INSERT INTO MAP_PROJECT_MANAGER VALUES (162, 1243);  --Paul Soffo > Paul Soffo
INSERT INTO MAP_PROJECT_MANAGER VALUES (216, 1244);  --Paula Cousins > Paula Cousins
INSERT INTO MAP_PROJECT_MANAGER VALUES (156, 1245);  --Peter Cocker > Peter Cocker
INSERT INTO MAP_PROJECT_MANAGER VALUES (299, 1246);  --Peter DeWith > Peter DeWith
INSERT INTO MAP_PROJECT_MANAGER VALUES (276, 1247);  --Peter Gooch > Peter Gooch
INSERT INTO MAP_PROJECT_MANAGER VALUES (334, 1248);  --Peter Yates > Peter Yates
INSERT INTO MAP_PROJECT_MANAGER VALUES (439, 1249);  --Phu Bui > Phu Bui
INSERT INTO MAP_PROJECT_MANAGER VALUES (360, 1250);  --Rachel Driedger > Rachel Driedger
INSERT INTO MAP_PROJECT_MANAGER VALUES (183, 1251);  --Ralph English > Ralph English
INSERT INTO MAP_PROJECT_MANAGER VALUES (60, 1252);  --Rampaul Dulay > Rampaul Dulay
INSERT INTO MAP_PROJECT_MANAGER VALUES (142, 1253);  --Randy Penner > Randy Penner
INSERT INTO MAP_PROJECT_MANAGER VALUES (337, 1254);  --Raouldy Hottua > Raouldy Hottua
INSERT INTO MAP_PROJECT_MANAGER VALUES (434, 1255);  --Raphael Avalos > Raphael Avalos
INSERT INTO MAP_PROJECT_MANAGER VALUES (186, 1256);  --Rebecca Huang > Rebecca Huang
INSERT INTO MAP_PROJECT_MANAGER VALUES (108, 1257);  --Reid Drummond > Reid Drummond
INSERT INTO MAP_PROJECT_MANAGER VALUES (394, 1258);  --Rena Gibson > Rena Gibson
INSERT INTO MAP_PROJECT_MANAGER VALUES (178, 1259);  --Richard Bush > Richard Bush
INSERT INTO MAP_PROJECT_MANAGER VALUES (235, 1260);  --Richard Lokken > Richard Lokken
INSERT INTO MAP_PROJECT_MANAGER VALUES (355, 1261);  --Rino Parise > Rino Parise
INSERT INTO MAP_PROJECT_MANAGER VALUES (81, 1262);  --Rob Kaleka > Rob Kaleka
INSERT INTO MAP_PROJECT_MANAGER VALUES (84, 1263);  --Robbie Kalabis > Robbie Kalabis
INSERT INTO MAP_PROJECT_MANAGER VALUES (113, 1264);  --Ron Domanko > Ron Domanko
INSERT INTO MAP_PROJECT_MANAGER VALUES (184, 1265);  --Ron Lowther > Ron Lowther
INSERT INTO MAP_PROJECT_MANAGER VALUES (396, 1266);  --Ron McCormack > Ron McCormack
INSERT INTO MAP_PROJECT_MANAGER VALUES (120, 1267);  --Ron Sharp > Ron Sharp
INSERT INTO MAP_PROJECT_MANAGER VALUES (140, 1268);  --Rosemary Barnewall > Rosemary Barnewall
INSERT INTO MAP_PROJECT_MANAGER VALUES (181, 1269);  --Ross Coates  > Ross Coates 
INSERT INTO MAP_PROJECT_MANAGER VALUES (215, 1270);  --Russ Roberts > Russ Roberts
INSERT INTO MAP_PROJECT_MANAGER VALUES (144, 1271);  --Ryan Edmonds > Ryan Edmonds
INSERT INTO MAP_PROJECT_MANAGER VALUES (226, 1272);  --Ryan Evanoff > Ryan Evanoff
INSERT INTO MAP_PROJECT_MANAGER VALUES (106, 1273);  --Ryan Oakley > Ryan Oakley
INSERT INTO MAP_PROJECT_MANAGER VALUES (255, 1274);  --Ryan Spillett > Ryan Spillett
INSERT INTO MAP_PROJECT_MANAGER VALUES (327, 1275);  --Ryan Thorpe > Ryan Thorpe
INSERT INTO MAP_PROJECT_MANAGER VALUES (121, 1276);  --Sam Pantaleo > Sam Pantaleo
INSERT INTO MAP_PROJECT_MANAGER VALUES (218, 1277);  --Samantha Kinnniburgh > Samantha Kinnniburgh
INSERT INTO MAP_PROJECT_MANAGER VALUES (309, 1278);  --Sandra Griffiths > Sandra Griffiths
INSERT INTO MAP_PROJECT_MANAGER VALUES (441, 1279);  --Sandy Lu > Sandy Lu
INSERT INTO MAP_PROJECT_MANAGER VALUES (344, 1280);  --Sarin Warman > Sarin Warman
INSERT INTO MAP_PROJECT_MANAGER VALUES (302, 1281);  --Satish Prasad > Satish Prasad
INSERT INTO MAP_PROJECT_MANAGER VALUES (385, 1282);  --Scott Hales > Scott Hales
INSERT INTO MAP_PROJECT_MANAGER VALUES (292, 1283);  --Scott Lain > Scott Lain
INSERT INTO MAP_PROJECT_MANAGER VALUES (36, 1284);  --Scotty Mckenzie > Scotty Mckenzie
INSERT INTO MAP_PROJECT_MANAGER VALUES (155, 1285);  --SCR- Jay Porter > SCR- Jay Porter
INSERT INTO MAP_PROJECT_MANAGER VALUES (330, 1286);  --Shaldon Datt > Shaldon Datt
INSERT INTO MAP_PROJECT_MANAGER VALUES (352, 1287);  --Shane Bennetts > Shane Bennetts
INSERT INTO MAP_PROJECT_MANAGER VALUES (321, 1288);  --Shannon Quarterman > Shannon Quarterman
INSERT INTO MAP_PROJECT_MANAGER VALUES (199, 1289);  --Sharon Goddard > Sharon Goddard
INSERT INTO MAP_PROJECT_MANAGER VALUES (307, 1290);  --Shaun HolaHan > Shaun HolaHan
INSERT INTO MAP_PROJECT_MANAGER VALUES (35, 1291);  --Shawn Clough > Shawn Clough
INSERT INTO MAP_PROJECT_MANAGER VALUES (45, 1292);  --Shawn Grant > Shawn Grant
INSERT INTO MAP_PROJECT_MANAGER VALUES (392, 1293);  --Shawn Haley > Shawn Haley
INSERT INTO MAP_PROJECT_MANAGER VALUES (91, 1294);  --Sheila Hui > Sheila Hui
INSERT INTO MAP_PROJECT_MANAGER VALUES (105, 1295);  --Shelby Snow > Shelby Snow
INSERT INTO MAP_PROJECT_MANAGER VALUES (191, 1296);  --Simon Lee > Simon Lee
INSERT INTO MAP_PROJECT_MANAGER VALUES (416, 1297);  --Spencer Holden > Spencer Holden
INSERT INTO MAP_PROJECT_MANAGER VALUES (65, 1298);  --Spencer King > Spencer King
INSERT INTO MAP_PROJECT_MANAGER VALUES (313, 1299);  --Stefan Yancey > Stefan Yancey
INSERT INTO MAP_PROJECT_MANAGER VALUES (315, 1300);  --Stephanie Daniels > Stephanie Daniels
INSERT INTO MAP_PROJECT_MANAGER VALUES (387, 1301);  --Stephanie Lorentz > Stephanie Lorentz
INSERT INTO MAP_PROJECT_MANAGER VALUES (102, 1302);  --Stephanie Rothman > Stephanie Rothman
INSERT INTO MAP_PROJECT_MANAGER VALUES (87, 1303);  --Stevan Sobat > Stevan Sobat
INSERT INTO MAP_PROJECT_MANAGER VALUES (224, 1304);  --Steve Dowling > Steve Dowling
INSERT INTO MAP_PROJECT_MANAGER VALUES (42, 1305);  --Steve Sirett > Steve Sirett
INSERT INTO MAP_PROJECT_MANAGER VALUES (201, 1306);  --Stew Miller > Stew Miller
INSERT INTO MAP_PROJECT_MANAGER VALUES (269, 1307);  --Stuart Johnson  > Stuart Johnson 
INSERT INTO MAP_PROJECT_MANAGER VALUES (359, 1308);  --Stuart Johnson > Stuart Johnson
INSERT INTO MAP_PROJECT_MANAGER VALUES (245, 1309);  --Susan Pearson > Susan Pearson
INSERT INTO MAP_PROJECT_MANAGER VALUES (166, 1310);  --Susan Randle > Susan Randle
INSERT INTO MAP_PROJECT_MANAGER VALUES (374, 1311);  --Susheela D'Souza > Susheela D''Souza
INSERT INTO MAP_PROJECT_MANAGER VALUES (223, 1312);  --Tammy Anderson > Tammy Anderson
INSERT INTO MAP_PROJECT_MANAGER VALUES (275, 1313);  --Tara Holmberg > Tara Holmberg
INSERT INTO MAP_PROJECT_MANAGER VALUES (272, 1314);  --Tara Jones > Tara Jones
INSERT INTO MAP_PROJECT_MANAGER VALUES (287, 1315);  --TBD TBD > TBD TBD
INSERT INTO MAP_PROJECT_MANAGER VALUES (109, 1316);  --Ted Moore > Ted Moore
INSERT INTO MAP_PROJECT_MANAGER VALUES (427, 1317);  --Terry Burns > Terry Burns
INSERT INTO MAP_PROJECT_MANAGER VALUES (438, 1318);  --Terry Burns > Terry Burns
INSERT INTO MAP_PROJECT_MANAGER VALUES (209, 1319);  --Terry Harbicht > Terry Harbicht
INSERT INTO MAP_PROJECT_MANAGER VALUES (219, 1320);  --Terry Murphy > Terry Murphy
INSERT INTO MAP_PROJECT_MANAGER VALUES (363, 1321);  --Theodore Hipol > Theodore Hipol
INSERT INTO MAP_PROJECT_MANAGER VALUES (103, 1322);  --Thomas Chhun  > Thomas Chhun 
INSERT INTO MAP_PROJECT_MANAGER VALUES (82, 1323);  --Tim Dyer > Tim Dyer
INSERT INTO MAP_PROJECT_MANAGER VALUES (230, 1324);  --Tim Meszaros > Tim Meszaros
INSERT INTO MAP_PROJECT_MANAGER VALUES (403, 1325);  --Tina Rogers > Tina Rogers
INSERT INTO MAP_PROJECT_MANAGER VALUES (375, 1326);  --Tomas Horalek > Tomas Horalek
INSERT INTO MAP_PROJECT_MANAGER VALUES (271, 1327);  --Tracey Raume > Tracey Raume
INSERT INTO MAP_PROJECT_MANAGER VALUES (190, 1328);  --Tracy Cooper > Tracy Cooper
INSERT INTO MAP_PROJECT_MANAGER VALUES (214, 1329);  --Tracy LeClair > Tracy LeClair
INSERT INTO MAP_PROJECT_MANAGER VALUES (71, 1330);  --Tracy Raume > Tracy Raume
INSERT INTO MAP_PROJECT_MANAGER VALUES (116, 1331);  --Trent Folk > Trent Folk
INSERT INTO MAP_PROJECT_MANAGER VALUES (95, 1332);  --Tricia Klein  > Tricia Klein 
INSERT INTO MAP_PROJECT_MANAGER VALUES (362, 1333);  --Trish Ryu > Trish Ryu
INSERT INTO MAP_PROJECT_MANAGER VALUES (123, 1334);  --Val Fabick > Val Fabick
INSERT INTO MAP_PROJECT_MANAGER VALUES (308, 1335);  --Val Hunsaker > Val Hunsaker
INSERT INTO MAP_PROJECT_MANAGER VALUES (208, 1336);  --Various  > Various 
INSERT INTO MAP_PROJECT_MANAGER VALUES (242, 1337);  --Victoria Godsaye-Simpson  > Victoria Godsaye-Simpson 
INSERT INTO MAP_PROJECT_MANAGER VALUES (277, 1338);  --Vince Trozzo > Vince Trozzo
INSERT INTO MAP_PROJECT_MANAGER VALUES (343, 1339);  --Vincent Ong > Vincent Ong
INSERT INTO MAP_PROJECT_MANAGER VALUES (131, 1340);  --Virginia Dragan > Virginia Dragan
INSERT INTO MAP_PROJECT_MANAGER VALUES (303, 1341);  --Wayne Byczek > Wayne Byczek
INSERT INTO MAP_PROJECT_MANAGER VALUES (73, 1342);  --Wes Wiebe > Wes Wiebe
INSERT INTO MAP_PROJECT_MANAGER VALUES (228, 1343);  --Will Zhang > Will Zhang
INSERT INTO MAP_PROJECT_MANAGER VALUES (241, 1344);  --Wim Jellema > Wim Jellema
INSERT INTO MAP_PROJECT_MANAGER VALUES (3, 1345);  --Wim Jellima > Wim Jellima
INSERT INTO MAP_PROJECT_MANAGER VALUES (398, 1346);  --Woongje Lee > Woongje Lee
INSERT INTO MAP_PROJECT_MANAGER VALUES (452, 1347);  --Zach Crippen > Zach Crippen
INSERT INTO MAP_PROJECT_MANAGER VALUES (274, 1348);  --Zach Staples > Zach Staples

COMMIT
GO


DECLARE @legacyCnt int, @crtCnt int, @mappedCnt int;

-- retrieve values from Legacy table
SELECT @legacyCnt = COUNT(*) 
FROM tblProjectManagers
WHERE Active = 1

--retrieve values from CRT Code Table
SELECT @crtCnt = COUNT(*) 
FROM CRT_CODE_LOOKUP
WHERE CODE_SET = 'PROJECT_MANAGER'
AND END_DATE IS NULL

SELECT @mappedCnt = COUNT(*) 
FROM MAP_PROJECT_MANAGER

PRINT CHAR(10) + 'Found ' + CONVERT(varchar, @legacyCnt) + ' Legacy Items and ' + CONVERT(varchar, @crtCnt) + ' CRT CodeLookup Items'
PRINT 'Mapped ' + CONVERT(varchar, @mappedCnt) + ' Total Items'

--SELECT * FROM MAP_PROJECT_MANAGER

BEGIN
	DECLARE @missing int;

	SELECT @missing = COUNT(*) 
	FROM tblProjects
	WHERE [Project Manager] IN (SELECT ID FROM 
		(SELECT * FROM MAP_PROJECT_MANAGER mpm
		RIGHT JOIN tblProjectManagers tpm
		ON tpm.ID = mpm.LEGACY_ID
		WHERE tpm.Active = 1) AS PM
		WHERE LEGACY_ID IS NULL)

	PRINT 'Found ' + CONVERT(varchar, @missing) + ' Projects linked to un-mapped Project Managers'
END

/*
-- Will find 93 projects linked to Project Manager ID 279 which is NULL, this is ok

SELECT [Project Manager], *
FROM tblProjects
WHERE [Project Manager] IN (SELECT ID FROM 
	(SELECT * FROM MAP_PROJECT_MANAGER mpm
	RIGHT JOIN tblProjectManagers tpm
	ON tpm.ID = mpm.LEGACY_ID
	WHERE tpm.Active = 1) AS PM
	WHERE LEGACY_ID IS NULL)

SELECT * FROM tblProjectManagers WHERE ID = 279
*/
