/* ---------------------------------------------------------------------- */
/* Target DBMS:           MS SQL Server 2017                              */
/* Project name:          Capital Rehabilitation Tracking Reporting       */
/* Author:                Ayodeji Kuponiyi                                */
/* Script type:           Database creation script                        */
/* Created on:            2021-01-11 22:51                                */
/* ---------------------------------------------------------------------- */

USE CRT_DEV;
GO


INSERT INTO CRT_REGION (REGION_NUMBER, REGION_NAME) VALUES (1,'South Coast');
INSERT INTO CRT_REGION (REGION_NUMBER, REGION_NAME) VALUES (2,'Southern Interior');
INSERT INTO CRT_REGION (REGION_NUMBER, REGION_NAME) VALUES (3,'Northern');


INSERT INTO CRT_DISTRICT (DISTRICT_NUMBER, DISTRICT_NAME, REGION_NUMBER) VALUES (1, 'Lower Mainland', (SELECT REGION_NUMBER FROM CRT_REGION WHERE REGION_NAME = 'South Coast'));
INSERT INTO CRT_DISTRICT (DISTRICT_NUMBER, DISTRICT_NAME, REGION_NUMBER) VALUES (2, 'Vancouver Island', (SELECT REGION_NUMBER FROM CRT_REGION WHERE REGION_NAME = 'South Coast'));
INSERT INTO CRT_DISTRICT (DISTRICT_NUMBER, DISTRICT_NAME, REGION_NUMBER) VALUES (3, 'Rocky Mountain', (SELECT REGION_NUMBER FROM CRT_REGION WHERE REGION_NAME = 'Southern Interior'));
INSERT INTO CRT_DISTRICT (DISTRICT_NUMBER, DISTRICT_NAME, REGION_NUMBER) VALUES (4, 'West Kootenay', (SELECT REGION_NUMBER FROM CRT_REGION WHERE REGION_NAME = 'Southern Interior'));
INSERT INTO CRT_DISTRICT (DISTRICT_NUMBER, DISTRICT_NAME, REGION_NUMBER) VALUES (5, 'Okanagan-Shuswap', (SELECT REGION_NUMBER FROM CRT_REGION WHERE REGION_NAME = 'Southern Interior'));
INSERT INTO CRT_DISTRICT (DISTRICT_NUMBER, DISTRICT_NAME, REGION_NUMBER) VALUES (6, 'Thompson-Nicola', (SELECT REGION_NUMBER FROM CRT_REGION WHERE REGION_NAME = 'Southern Interior'));
INSERT INTO CRT_DISTRICT (DISTRICT_NUMBER, DISTRICT_NAME, REGION_NUMBER) VALUES (7, 'Cariboo', (SELECT REGION_NUMBER FROM CRT_REGION WHERE REGION_NAME = 'Southern Interior'));
INSERT INTO CRT_DISTRICT (DISTRICT_NUMBER, DISTRICT_NAME, REGION_NUMBER) VALUES (8, 'Peace', (SELECT REGION_NUMBER FROM CRT_REGION WHERE REGION_NAME = 'Northern'));
INSERT INTO CRT_DISTRICT (DISTRICT_NUMBER, DISTRICT_NAME, REGION_NUMBER) VALUES (9, 'Fort George', (SELECT REGION_NUMBER FROM CRT_REGION WHERE REGION_NAME = 'Northern'));
INSERT INTO CRT_DISTRICT (DISTRICT_NUMBER, DISTRICT_NAME, REGION_NUMBER) VALUES (10, 'Bulkley-Stikine', (SELECT REGION_NUMBER FROM CRT_REGION WHERE REGION_NAME = 'Northern'));
INSERT INTO CRT_DISTRICT (DISTRICT_NUMBER, DISTRICT_NAME, REGION_NUMBER) VALUES (11, 'Skeena', (SELECT REGION_NUMBER FROM CRT_REGION WHERE REGION_NAME = 'Northern'));



INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (1, 'South Island', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Vancouver Island'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (2, 'Central Island', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Vancouver Island'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (3, 'North Island', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Vancouver Island'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (4, 'Howe Sound', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Lower Mainland'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (5, 'Sunshine Coast', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Lower Mainland'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (6, 'Lower Mainland', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Lower Mainland'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (7, 'Fraser Valley', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Lower Mainland'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (8, 'South Okanagan', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Okanagan-Shuswap'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (9, 'Kootenay Boundary', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'West Kootenay'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (10, 'Central Kootenay', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'West Kootenay'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (11, 'East Kootenay', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Rocky Mountain'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (12, 'Selkirk', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Rocky Mountain'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (13, 'Okanagan-Shuswap', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Okanagan-Shuswap'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (14, 'Nicola', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Thompson-Nicola'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (15, 'Thompson', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Thompson-Nicola'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (16, 'South Cariboo', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Cariboo'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (17, 'Central Cariboo', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Cariboo'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (18, 'North Cariboo', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Cariboo'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (19, 'Fort George', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Fort George'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (20, 'Robson', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Fort George'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (21, 'South Peace', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Peace'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (22, 'North Peace', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Peace'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (23, 'Nechako', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Fort George'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (24, 'Lakes', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Bulkley-Stikine'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (25, 'Bulkley Nass', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Bulkley-Stikine'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (26, 'Skeena', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Skeena'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (27, 'North Coast', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Skeena'));
INSERT INTO CRT_SERVICE_AREA (SERVICE_AREA_NUMBER, SERVICE_AREA_NAME, DISTRICT_NUMBER) VALUES (28, 'Stikine', (SELECT DISTRICT_NUMBER FROM CRT_DISTRICT WHERE DISTRICT_NAME = 'Bulkley-Stikine'));


