/*
Author - Ayodeji Kuponiyi
Date- May 05, 2021
Sprint 9

Instruction
- to be run after the views are built on the database
*/

USE CRT_DEV;
GO

-- GRANT select on views

GRANT SELECT ON dbo.CRT_PROGRAM_PROJECT_FINANCIAL_REPORT_VW TO CRT_READ_ONLY
GRANT SELECT ON dbo.CRT_PRJ_QTY_ACCOMPLISHMENT_REPORT_VW TO CRT_READ_ONLY
GRANT SELECT ON dbo.CRT_PROJECT_TENDER_REPORT_VW TO CRT_READ_ONLY
GRANT SELECT ON dbo.CRT_PROJECT_SEGMENT_REPORT_VW TO CRT_READ_ONLY
GRANT SELECT ON dbo.CRT_PROJECT_NOTE_REPORT_VW TO CRT_READ_ONLY
GRANT SELECT ON dbo.CRT_PROJECT_RATIO_REPORT_VW TO CRT_READ_ONLY
GRANT SELECT ON dbo.CRT_PROJECT_REPORT_VW TO CRT_READ_ONLY


--GRANT select on all tables
GRANT SELECT ON [dbo].[CRT_CODE_LOOKUP]  TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_CODE_LOOKUP_HIST]  TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_DISTRICT] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_ELEMENT] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_ELEMENT_HIST] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_FIN_TARGET] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_FIN_TARGET_HIST] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_NOTE] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_NOTE_HIST] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_PERMISSION] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_PERMISSION_HIST] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_PROJECT] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_PROJECT_HIST] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_QTY_ACCMP] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_QTY_ACCMP_HIST] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_RATIO] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_RATIO_HIST] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_REGION] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_REGION_DISTRICT] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_REGION_DISTRICT_HIST] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_REGION_USER] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_REGION_USER_HIST] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_ROLE] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_ROLE_HIST] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_ROLE_PERMISSION] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_ROLE_PERMISSION_HIST] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_SEGMENT] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_SEGMENT_HIST] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_SERVICE_AREA] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_SERVICE_AREA_HIST] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_SYSTEM_USER] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_SYSTEM_USER_HIST] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_TENDER] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_TENDER_HIST] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_USER_ROLE] TO CRT_READ_ONLY
GRANT SELECT ON [dbo].[CRT_USER_ROLE_HIST] TO CRT_READ_ONLY


GO

