export const PROJECT_HELPER_TEXT = {
  projectNumber: `Manually assigned by financial ee's using an H0277 form`,
  projectName: `Typically created by project manager using project naming conventions`,
  description: `Non-technical description of the project; meant for public consumption`,
  scope: `Technical description, meant for internal consumption`,
  capIndxLkupId: `A value assigned to indicate whether expenditures related to a project are capitalizable (contributes to extending the life of an asset) or expensable (does not materially contribute to extending the life of an asset)`,
  rcLkupId: `Financial Code`,
  projectMgrId: `Key contact for the project`,
  nearstTwnLkupId: `Used to report on project outcomes`,
  endDate: `End Date is selected to mark the project as complete`,
  tenderNumber: `Identifier for the tender <project#>-####`,
  plannedDate: `Planned date for posting Tender at Provincial Contracts`,
  actualDate: `Actual date for posting Tender at Provincial Contracts`,
  tenderValue: `Dollar value of the Tender`,
  winningCntrctrLkupId: `Contractor that wins the tender`,
  bidValue: `Dollar value of the winning bid`,
  anncmentValue: `Project value as communicated through announcement done by GCPE`,
  c035Value: `Value on the road side signs for the project value`,
  anncmentComment: `Comments on project announcements`,
};
