export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_USER_TYPES = 'FETCH_USER_TYPES';
export const FETCH_USER_STATUSES = 'FETCH_USER_STATUSES';

export const FETCH_REGIONS = 'FETCH_REGIONS';

// Global Error Dialog
export const SHOW_ERROR_DIALOG_MODAL = 'SHOW_ERROR_DIALOG_MODAL';
export const HIDE_ERROR_DIALOG_MODAL = 'HIDE_ERROR_DIALOG_MODAL';
