export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_USER_TYPES = 'FETCH_USER_TYPES';
export const FETCH_USER_STATUSES = 'FETCH_USER_STATUSES';
export const FETCH_PROJECT_MANAGERS = 'FETCH_PROJECT_MANAGERS';

//lookups
export const FETCH_REGIONS = 'FETCH_REGIONS';

//code table lookups
export const FETCH_CAPITAL_INDEXES = 'FETCH_CAPITAL_INDEXES';
export const FETCH_RC_NUMBERS = 'FETCH_RC_NUMBERS';
export const FETCH_NEAREST_TOWNS = 'FETCH_NEAREST_TOWNS';
export const FETCH_PHASES = 'FETCH_PHASES';
export const FETCH_FISCAL_YEARS = 'FETCH_FISCAL_YEARS';
export const FETCH_QUANTITIES = 'FETCH_QUANTITIES';
export const FETCH_ACCOMPLISHMENTS = 'FETCH_ACCOMPLISHMENTS';
export const FETCH_CONTRACTORS = 'FETCH_CONTRACTORS';
export const FETCH_FUNDING_TYPES = 'FETCH_FUNDING_TYPES';
export const FETCH_ELEMENTS = 'FETCH_ELEMENTS';

// Global Error Dialog
export const SHOW_ERROR_DIALOG_MODAL = 'SHOW_ERROR_DIALOG_MODAL';
export const HIDE_ERROR_DIALOG_MODAL = 'HIDE_ERROR_DIALOG_MODAL';

//Search History
export const SET_PROJECT_SEARCH_HISTORY = 'SET_PROJECT_SEARCH_HISTORY';
export const SET_PROJECT_SEARCH_FORMIK_VALUES = 'SET_PROJECT_SEARCH_FORMIK_VALUES';
export const RESET_PROJECT_SEARCH_FORMIK_VALUES = 'RESET_PROJECT_SEARCH_FORMIK_VALUES';
